<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Fixture.BuildAssets</PackageId>
    <PackageVersion>1.0.0</PackageVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <PackageTags>fixture;nuget;build-assets</PackageTags>
    <RepositoryUrl>https://github.com/KeelMatrix/NuGetReady</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="README.md" />
    <None Include="../../../../icon.png" Pack="true" PackagePath="icon.png" />
    <None Include="buildTransitive\Fixture.BuildAssets.props" Pack="true" PackagePath="buildTransitive\Fixture.BuildAssets.props" />
  </ItemGroup>
</Project>
